/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class win32_Win32GUI */

#ifndef _Included_win32_Win32GUI
#define _Included_win32_Win32GUI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     win32_Win32GUI
 * Method:    EnumWindows
 * Signature: (Lwin32/EnumFunction;)Z
 */
JNIEXPORT jboolean JNICALL Java_win32_Win32GUI_EnumWindows
  (JNIEnv *, jclass, jobject);

/*
 * Class:     win32_Win32GUI
 * Method:    EnumChildWindows
 * Signature: (ILwin32/EnumFunction;)V
 */
JNIEXPORT void JNICALL Java_win32_Win32GUI_EnumChildWindows
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     win32_Win32GUI
 * Method:    GetLastError
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_win32_Win32GUI_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     win32_Win32GUI
 * Method:    GetWindowText
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_win32_Win32GUI_GetWindowText
  (JNIEnv *, jclass, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetClassName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_win32_Win32GUI_GetClassName
  (JNIEnv *, jclass, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetMenu
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_GetMenu
  (JNIEnv *, jclass, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetMenuItemCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_GetMenuItemCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetMenuItemID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_GetMenuItemID
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    PostMessage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_win32_Win32GUI_PostMessage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetMenuState
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_GetMenuState
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetSubMenu
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_GetSubMenu
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetMenuString
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_win32_Win32GUI_GetMenuString
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    SendMessage
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_SendMessage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    SendMessageWithString
 * Signature: (IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_SendMessageWithString
  (JNIEnv *, jclass, jint, jint, jint, jstring);

/*
 * Class:     win32_Win32GUI
 * Method:    SendMessageReturnString
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_win32_Win32GUI_SendMessageReturnString
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetParent
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_GetParent
  (JNIEnv *, jclass, jint);

/*
 * Class:     win32_Win32GUI
 * Method:    GetWindowLong
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_win32_Win32GUI_GetWindowLong
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
